export const DEFAULT_POCKET_CONFIG = {
  MAX_DISPATCHERS: 50,
  MAX_SESSIONS: 100000,
  CONSENSUS_NODE_COUNT: 0,
  REQUEST_TIMEOUT: 120000, // 3 minutes
  ACCEPT_DISPUTED_RESPONSES: false,
  VALIDATE_RELAY_RESPONSES: undefined,
  REJECT_SELF_SIGNED_CERTIFICATES: undefined,
  USE_LEGACY_TX_CODEC: true,
}
