version: "3.5"

services:
  gateway:
    image: pocket-network/gateway
    container_name: gateway
    build:
      context: ..
      dockerfile: ./Dockerfile
    command: npm run start:watch
    env_file:
      - ../.env
    ports:
      - 3000:3000
    volumes:
      - "../src:/usr/src/gateway/src"
      - "../dist:/usr/src/gateway/dist"
    depends_on:
      - db
      - cache
      - metricsdb
    networks:
      - pocket

  db:
    image: mongo:4.2.14
    container_name: db
    env_file:
      - ../.tasks.env
    volumes: 
      - ~/.pocket/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - pocket
  
  cache:
    image: "redis:alpine"
    container_name: cache
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - pocket

  metricsdb:
    container_name: metricsdb
    image: timescale/timescaledb:2.0.2-pg12
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=gatewaydb
    ports:
      - 5432:5432
    networks:
      - pocket

networks:
  pocket:
    driver: bridge
