version: "3.5"

services:
  gateway:
    image: pocket-network/gateway
    build:
      context: ..
      dockerfile: ./Dockerfile
    command: npm run start:watch
    env_file:
      - ../.env
    ports:
      - 3000:3000
    volumes:
      - "../src:/usr/src/gateway/src"
      - "../dist:/usr/src/gateway/dist"
    networks:
      - pocket

  db:
    image: mongo:latest
    env_file:
      - ../.tasks.env
    volumes: 
      - ~/.pocket/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - pocket
  
  cache:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - pocket

  metricsdb:
    image: timescale/timescaledb:2.0.2-pg12
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=gatewaydb
    ports:
      - 5432:5432
    networks:
      - pocket    

  s3:
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: gatewayS3AccessKeyId
      MINIO_SECRET_KEY: gatewayS3SecretAccessKey

networks:
  pocket:
    driver: bridge
