version: '3.5'

services:
  gateway:
    image: pocket-network/gateway
    container_name: gateway
    build:
      context: ..
      dockerfile: ./Dockerfile
    command: npm run start:watch
    env_file:
      - ../.env
    ports:
      - 3000:3000
    volumes:
      - '../src:/usr/src/gateway/src'
      - '../dist:/usr/src/gateway/dist'
    depends_on:
      - db
      - cache
      - errorsdb
    networks:
      - pocket

  db:
    image: mongo:5.0.6
    container_name: db
    env_file:
      - ../.tasks.env
    volumes:
      - ~/.pocket/mongodb:/data/db
    ports:
      - '27017:27017'
    networks:
      - pocket

  cache:
    image: 'redis:alpine'
    container_name: cache
    command: redis-server
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - pocket

  local-cache:
    image: 'redis:alpine'
    container_name: local-cache
    command: redis-server
    ports:
      - '6380:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - pocket

  # DB to store errors
  errorsdb:
    image: postgres:15.1
    container_name: errorsdb
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=gateway
    ports:
      - 5432:5432
    networks:
      - pocket
    volumes:
      - ../scripts/error.init.sql:/docker-entrypoint-initdb.d/init.sql

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: influxdb
    volumes:
      - influxdb:/.influxdbv2
    ports:
      - '8086:8086'
    networks:
      - pocket

  influxdb_cli:
    links:
      - influxdb
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: influxdb_cli
    entrypoint: influx setup --bucket mainnetRelayStaging -t mytoken -o myorg --username=influxuser --password=influxpassword --host=http://influxdb:8086 -f
    restart: on-failure:10
    depends_on:
      - influxdb
    networks:
      - pocket

  telegraf:
    image: telegraf
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb_cli
    networks:
      - pocket

volumes:
  influxdb:

networks:
  pocket:
    driver: bridge
