name: Cherry Picker Discord Alert
on:
  pull_request:
    branches: [develop]
    paths:
      - 'src/services/cherry-picker.ts'
jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare discord embed
        id: discord-embed
        run: |
          echo ::set-output name=json_var::'[{\n    \"title\": \"Hello!\",\n    \"description\": \"Hi! :grinning:\"\n  }]'

      - name: Print discord embed
        env:
          EMBED: ${{ steps.discord-embed.outputs.json_var }}
        run: |
          echo $EMBED

      - name: Send discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: ${{ toJSON(steps.discord-embed.outputs.json_var) }}
        uses: Ilshidur/action-discord@master