name: Cherry Picker Discord Alert
on:
  pull_request:
    branches: [develop]
    paths:
      - 'src/services/cherry-picker.ts'
jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          PR_NUMBER: ${{ github.event.number }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'A new pull request (#{{ PR_NUMBER }}) that modifies cherry picker has been detected.'
