name: Cherry Picker Discord Alert
on:
  pull_request:
    branches: [develop]
    paths:
      - 'src/services/cherry-picker.ts'
jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'A new pull request that modifies the cherry picker has been submitted.'
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master